import type {
  FinalExportReceipt,
  Finding,
  PreflightReport,
  ReleaseContract,
  RevisionCheckReport,
  RevisionReceipt,
  VerificationReport,
} from "./preflight";

export interface ProofArtifact {
  relative_path: string;
  sha256: string;
  size_bytes: number;
  mime_type: string;
}

export interface ReceiptVerificationResult {
  status: "VALID" | "MISMATCH" | "INVALID_RECEIPT" | "INCOMPLETE_VERIFICATION";
  receipt_kind: "FINAL_EXPORT" | "REVISION" | null;
  recorded_verdict: string | null;
  recorded_completeness: string | null;
  checks: string[];
  mismatches: string[];
}

export interface JudgeProofBundle {
  schema_version: "1.0";
  generator_version: "1";
  generation_origin: "GENERATED_FROM_ENGINE";
  generated_at: string;
  provenance: {
    source_type: "public_domain" | "generated_control";
    source_credit: string;
    source_title: string;
    source_url: string | null;
    source_sha256: string;
    owner_demo_generator_version: string | null;
  };
  final_export: {
    generation_origin: "GENERATED_FROM_ENGINE";
    original_video: ProofArtifact;
    repaired_video: ProofArtifact;
    thumbnail: ProofArtifact;
    title: string;
    description: string;
    original_report: PreflightReport;
    repair_operation: { operation_type: "REMOVE_RANGE"; start_seconds: number; end_seconds: number };
    verification: VerificationReport;
    receipt: FinalExportReceipt;
    receipt_valid: ReceiptVerificationResult;
    receipt_mutated_artifact: ReceiptVerificationResult;
  };
  release_contract: {
    generation_origin: "GENERATED_FROM_ENGINE";
    provenance: JudgeProofBundle["provenance"];
    video: ProofArtifact;
    captions: ProofArtifact;
    title: string;
    description: string;
    contract: ReleaseContract;
    report: PreflightReport;
  };
  revision: {
    generation_origin: "GENERATED_FROM_ENGINE";
    previous_video: ProofArtifact;
    revised_video: ProofArtifact;
    notes: string;
    report: RevisionCheckReport;
    receipt: RevisionReceipt;
    receipt_valid: ReceiptVerificationResult;
  };
}

export function parseJudgeProofBundle(value: unknown): JudgeProofBundle {
  if (!isRecord(value) || value.schema_version !== "1.0" || value.generator_version !== "1" || value.generation_origin !== "GENERATED_FROM_ENGINE") {
    throw new Error("Judge proof bundle has an unsupported schema or provenance.");
  }
  for (const key of ["final_export", "release_contract", "revision"] as const) {
    const item = value[key];
    if (!isRecord(item) || item.generation_origin !== "GENERATED_FROM_ENGINE") {
      throw new Error("Judge proof case was not generated by the engine.");
    }
  }
  return value as unknown as JudgeProofBundle;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function timedFindings(findings: Finding[]): Finding[] {
  return findings.filter((finding) => finding.timestamp_start_seconds !== null);
}
