import { render, screen, within } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import proofBundle from "../public/proof/judge-proof.json";
import { JudgeProofApp } from "./JudgeProofApp";
import { parseJudgeProofBundle } from "./types/judgeProof";

beforeEach(() => {
  vi.stubGlobal("fetch", vi.fn().mockResolvedValue({ ok: true, json: async () => proofBundle }));
});

describe("Judge Proof Mode", () => {
  it("renders authoritative generated engine evidence with a visible disclosure", async () => {
    render(<JudgeProofApp />);
    expect(await screen.findByRole("heading", { name: /Creator Preflight proves the final release/i })).toBeInTheDocument();
    expect(screen.getByText(/precomputed, reproducible evidence/i)).toBeInTheDocument();
    expect(screen.getByText(/generated by the real Creator Preflight engine/i)).toBeInTheDocument();
    expect(screen.getByText(/attribution does not imply endorsement/i)).toBeInTheDocument();
    expect(screen.getAllByText("NEEDS REVIEW").length).toBeGreaterThan(0);
    expect(screen.getAllByText("0", { selector: ".proof-metric strong" }).length).toBeGreaterThan(0);
    expect(screen.getByText("unexpected media changes")).toBeInTheDocument();
  });

  it("shows real contract, revision, receipt, and package proof facts", async () => {
    render(<JudgeProofApp />);
    const requirements = await screen.findByRole("heading", { name: "Release Requirements" });
    expect(within(requirements.closest("section")!).getAllByText(/SAVE20/).length).toBeGreaterThan(0);
    expect(screen.getByText("94.3%")).toBeInTheDocument();
    expect(screen.getByText("Correct artifact: VALID")).toBeInTheDocument();
    expect(screen.getByText("One-byte mutation: MISMATCH")).toBeInTheDocument();
    expect(screen.getByAltText("Authentic Yellowstone thumbnail")).toHaveAttribute("src", expect.stringContaining("yellowstone-thumbnail.jpg"));
    expect(screen.getByText("3:32")).toBeInTheDocument();
  });

  it("rejects proof data without generated-engine provenance", () => {
    expect(() => parseJudgeProofBundle({ ...proofBundle, generation_origin: "HAND_AUTHORED" })).toThrow(/schema or provenance/i);
    expect(() => parseJudgeProofBundle({ ...proofBundle, revision: { ...proofBundle.revision, generation_origin: "HAND_AUTHORED" } })).toThrow(/not generated by the engine/i);
  });
});
