import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight, Check, FileCheck2, Play, ShieldCheck, TriangleAlert, Wrench } from "lucide-react";
import { PRODUCT_NAME } from "./brand";
import type { JudgeProofBundle, ProofArtifact } from "./types/judgeProof";
import { parseJudgeProofBundle, timedFindings } from "./types/judgeProof";
import { formatTimecode } from "./utils/format";

const proofBase = `${import.meta.env.BASE_URL}proof/`;

export function JudgeProofApp() {
  const [bundle, setBundle] = useState<JudgeProofBundle | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    fetch(`${proofBase}judge-proof.json`)
      .then((response) => response.ok ? response.json() : Promise.reject(new Error("Judge proof evidence could not be loaded.")))
      .then((value) => setBundle(parseJudgeProofBundle(value)))
      .catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Judge proof evidence could not be loaded."));
  }, []);
  if (error) return <main className="proof-load-state"><h1>Judge Proof unavailable</h1><p>{error}</p></main>;
  if (!bundle) return <main className="proof-load-state"><h1>Loading verified evidence…</h1></main>;
  return <Proof bundle={bundle} />;
}

function Proof({ bundle }: { bundle: JudgeProofBundle }) {
  const final = bundle.final_export;
  const contract = bundle.release_contract;
  const revision = bundle.revision;
  const originalRef = useRef<HTMLVideoElement>(null);
  const contractFailure = contract.report.release_contract.results.find((item) => item.status === "FAIL");
  const packageSummary = final.original_report.release_package;
  const thumbUrl = assetUrl(final.thumbnail);
  const repairDuration = final.repair_operation.end_seconds - final.repair_operation.start_seconds;
  const unchanged = revision.report.revision_map.unchanged_ratio * 100;
  const findings = timedFindings(final.original_report.findings);
  const packageRows = useMemo(() => [
    ["Video", packageSummary.video], ["Thumbnail", packageSummary.thumbnail], ["Captions", packageSummary.captions],
    ["Title", packageSummary.title], ["Description", packageSummary.description], ["Chapters", packageSummary.chapters],
    ["Release requirements", packageSummary.release_contract],
  ] as const, [packageSummary]);

  function seekOriginal(seconds: number) {
    if (!originalRef.current) return;
    originalRef.current.currentTime = seconds;
    void originalRef.current.play();
  }

  return <div className="proof-shell">
    <header className="proof-header"><span>{PRODUCT_NAME}</span><a href={import.meta.env.BASE_URL}>Open full application</a></header>
    <main className="proof-main">
      <section className="proof-hero">
        <p className="proof-eyebrow">Judge Proof Mode</p>
        <h1>AI can make the edit. Creator Preflight proves the final release is ready to ship.</h1>
        <p>Inspect real, portable evidence for export checks, repair verification, release requirements, revision comparison, and exact artifact identity.</p>
      </section>
      <aside className="proof-disclosure"><ShieldCheck aria-hidden="true" /><span><strong>Precomputed, reproducible evidence.</strong> Judge Proof Mode uses results generated by the real Creator Preflight engine from committed/reproducible fixtures. Run the full app locally to scan arbitrary files.</span></aside>

      <nav className="proof-nav" aria-label="Proof sections">
        {[["A", "Final Export"], ["B", "Repair Verification"], ["C", "Release Requirements"], ["D", "Revision"], ["E", "Release Receipt"]].map(([letter, label]) => <a key={letter} href={`#proof-${letter.toLowerCase()}`}><span>{letter}</span>{label}</a>)}
      </nav>

      <ProofSection id="proof-a" label="A" title="Final Export" lead="The authentic Yellowstone release is checked as one complete package.">
        <div className="proof-two-column">
          <div className="proof-media-card">
            <video ref={originalRef} controls preload="metadata" poster={thumbUrl} src={assetUrl(final.original_video)} aria-label="Authentic Yellowstone Final Export" />
            <div className="proof-media-meta"><strong>{final.title}</strong><span>{bundle.provenance.source_credit} · {bundle.provenance.source_type.replace("_", " ")} · attribution does not imply endorsement</span></div>
          </div>
          <div className="proof-fact-panel">
            <ProofMetric value={final.original_report.verdict.replace("_", " ")} label={`${final.original_report.scan_completeness.toLowerCase()} scan`} tone="review" />
            <h3>Timestamped engine findings</h3>
            <ul className="proof-evidence-list">{findings.map((finding) => <li key={`${finding.code}-${finding.timestamp_start_seconds}`}><button onClick={() => seekOriginal(finding.timestamp_start_seconds ?? 0)}><Play aria-hidden="true" /><span><strong>{finding.details?.title?.toString() ?? finding.code}</strong><small>{formatTimecode(finding.timestamp_start_seconds ?? 0)} · seek real evidence</small></span></button></li>)}</ul>
          </div>
        </div>
        <div className="proof-package-grid">
          <div className="proof-package-summary"><h3>Release package</h3>{packageRows.map(([label, component]) => <div key={label}>{component.state === "PRESENT_VALID" ? <Check aria-hidden="true" /> : <span className="proof-neutral-mark" aria-hidden="true">—</span>}<span><strong>{label}</strong><small>{component.detail}</small></span></div>)}</div>
          <div className="proof-thumbnail-preview"><h3>Actual thumbnail delivery preview</h3><div className="proof-thumb-stage"><img src={thumbUrl} alt="Authentic Yellowstone thumbnail" /><span>{packageSummary.delivery_preview?.duration_badge_text}</span></div><p>{packageSummary.thumbnail_width}×{packageSummary.thumbnail_height} · {packageSummary.delivery_preview?.surfaces.map((surface) => `${surface.label} ${surface.display_width}×${surface.display_height}`).join(" · ")}</p><small>Geometric delivery preview only; no legibility or saliency score.</small></div>
        </div>
      </ProofSection>

      <ProofSection id="proof-b" label="B" title="Repair Verification" lead="The backend removes only the approved range, scans the repaired export again, and checks unaffected media.">
        <div className="proof-metric-row">
          <ProofMetric value="1" label="target resolved" tone="pass" />
          <ProofMetric value={String(final.verification.remaining.length)} label="still need attention" />
          <ProofMetric value={String(final.verification.new.length)} label="new findings" />
          <ProofMetric value={String(final.verification.unexpected_changes.length)} label="unexpected media changes" tone="pass" />
        </div>
        <div className="proof-repair-flow"><div><Wrench aria-hidden="true" /><strong>Remove {formatTimecode(final.repair_operation.start_seconds)}–{formatTimecode(final.repair_operation.end_seconds)}</strong><span>Approved bounded operation · {repairDuration.toFixed(2)} seconds removed</span></div><ArrowRight aria-hidden="true" /><div><FileCheck2 aria-hidden="true" /><strong>Repaired export re-scanned</strong><span>{formatTimecode(final.verification.original_duration_seconds)} → {formatTimecode(final.verification.repaired_duration_seconds)}</span></div></div>
        <video className="proof-wide-video" controls preload="metadata" src={assetUrl(final.repaired_video)} aria-label="Repaired Yellowstone export" />
      </ProofSection>

      <ProofSection id="proof-c" label="C" title="Release Requirements" lead="Technically acceptable media can still be the wrong delivery.">
        <div className="proof-contract-callout"><TriangleAlert aria-hidden="true" /><div><strong>BLOCKED by an actual deterministic requirement</strong><p>{contractFailure?.instruction}</p><p>{contractFailure?.evidence}</p></div></div>
        <div className="proof-requirement-grid">{contract.report.release_contract.results.map((result) => <div key={result.requirement_id} className={`proof-requirement proof-${result.status.toLowerCase()}`}><span>{result.status}</span><strong>{result.instruction}</strong><small>{result.evidence}</small></div>)}</div>
        <p className="proof-source-note">Text evidence source: supplied caption file <code>{contract.captions.relative_path.split("/").at(-1)}</code>. No provider call was used.</p>
      </ProofSection>

      <ProofSection id="proof-d" label="D" title="Revision" lead="Previous and Revised stay side by side; requested changes remain separate from additional physical changes.">
        <div className="proof-metric-row"><ProofMetric value={`${unchanged.toFixed(1)}%`} label="unchanged" tone="pass" /><ProofMetric value={String(revision.report.requested_changes_detected_count)} label="requested areas changed" tone="pass" /><ProofMetric value={String(revision.report.requested_changes_not_detected_count)} label="requested areas unchanged" /><ProofMetric value={String(revision.report.additional_change_count)} label="additional change" tone="review" /></div>
        <div className="proof-video-pair"><div><strong>Previous</strong><video controls preload="metadata" src={assetUrl(revision.previous_video)} /></div><div><strong>Revised</strong><video controls preload="metadata" src={assetUrl(revision.revised_video)} /></div></div>
        <div className="proof-revision-list">{revision.report.revision_requests.map((request) => <div key={request.request_id}><Check aria-hidden="true" /><span><strong>{request.text}</strong><small>{request.status.replaceAll("_", " ")} · {request.evidence}</small></span></div>)}{revision.report.additional_changes.map((change) => <div key={change.segment_id}><TriangleAlert aria-hidden="true" /><span><strong>Additional physical change</strong><small>Previous {formatTimecode(change.previous_start_seconds ?? 0)}–{formatTimecode(change.previous_end_seconds ?? 0)} · {change.visual_changed ? "visual" : "audio"} evidence</small></span></div>)}</div>
      </ProofSection>

      <ProofSection id="proof-e" label="E" title="Release Receipt" lead="A machine-verifiable receipt records exactly which artifact and package were checked.">
        <div className="proof-receipt-grid"><ReceiptFact label="Shipping artifact" value={shortHash(final.receipt.package.shipping_video.sha256)} /><ReceiptFact label="Recorded verdict" value={final.receipt.verdict.replace("_", " ")} /><ReceiptFact label="Package fingerprint" value={shortHash(final.receipt.package.package_fingerprint_sha256)} /><ReceiptFact label="Receipt digest" value={shortHash(final.receipt.receipt_content_sha256)} /></div>
        <div className="proof-verifier-pair"><div className="proof-valid"><Check aria-hidden="true" /><strong>Correct artifact: {final.receipt_valid.status}</strong><span>{final.receipt_valid.checks.join(" ")}</span></div><div className="proof-mismatch"><TriangleAlert aria-hidden="true" /><strong>One-byte mutation: {final.receipt_mutated_artifact.status}</strong><span>{final.receipt_mutated_artifact.mismatches.join(" ")}</span></div></div>
        <p className="proof-source-note">The digest detects modification when it no longer matches the payload. It is not a digital signature or third-party attestation.</p>
      </ProofSection>
    </main>
    <footer className="proof-footer">Generated from the production engine · bundle schema {bundle.schema_version} · <a href={`${proofBase}judge-proof.json`}>inspect authoritative JSON</a></footer>
  </div>;
}

function ProofSection({ id, label, title, lead, children }: { id: string; label: string; title: string; lead: string; children: React.ReactNode }) {
  return <section className="proof-section" id={id}><header><span>{label}</span><div><h2>{title}</h2><p>{lead}</p></div></header>{children}</section>;
}
function ProofMetric({ value, label, tone = "neutral" }: { value: string; label: string; tone?: "neutral" | "pass" | "review" }) { return <div className={`proof-metric proof-metric-${tone}`}><strong>{value}</strong><span>{label}</span></div>; }
function ReceiptFact({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function assetUrl(item: ProofArtifact) { return `${proofBase}${item.relative_path}`; }
function shortHash(value: string) { return `${value.slice(0, 10)}…${value.slice(-8)}`; }
